ChuteCampeao.MVC/Controllers/EstadioController.cs
using AutoMapper;
using ChuteCampeao.Domain.Entites;
using ChuteCampeao.Domain.Interfaces.Services;
using ChuteCampeao.Infra.Data.Repositories;
using ChuteCampeao.MVC.Helpers;
using ChuteCampeao.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuteCampeao.MVC.Controllers
{
    public class EstadioController : Controller
    {
        private readonly IEstadioService _estadioService;

        public EstadioController(IEstadioService estadioService)
        {
            this._estadioService = estadioService;
        }

        public ActionResult Index()
        {
            var data = Mapper.Map<IEnumerable<Estadio>, IEnumerable<EstadioVM>>(_estadioService.GetAll());
            return View(data);
        }

        public ActionResult Criar()
        {
            EstadioVM estadioVM = new EstadioVM() {
                LstStatus = Utils.ListarStatus()
            };
            return View(estadioVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(EstadioVM model)
        {
            _estadioService.Add(Mapper.Map<Estadio>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Detalhes(int id)
        {
            return View(Mapper.Map<EstadioVM>(_estadioService.GetById(id)));
        }

        public ActionResult Editar(int id)
        {
            EstadioVM data = Mapper.Map<EstadioVM>(_estadioService.GetById(id));
            data.LstStatus = Utils.ListarStatus();
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(EstadioVM model)
        {
            _estadioService.Update(Mapper.Map<Estadio>(model));
            return RedirectToAction("Index"); 
        }
        
        public ActionResult Deletar(int id)
        {
            _estadioService.RemoveById(id);
            return RedirectToAction("Index");
        }
    }
}

ChuteCampeao.MVC/Controllers/PartidaController.cs
using AutoMapper;
using ChuteCampeao.Domain.Entites;
using ChuteCampeao.Domain.Interfaces.Services;
using ChuteCampeao.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuteCampeao.MVC.Controllers
{
    public class PartidaController : Controller
    {
        private readonly IPartidaService _partidaService;

        public PartidaController(IPartidaService partidaService)
        {
            this._partidaService = partidaService;
        }

        public ActionResult Index()
        {
            var data = Mapper.Map<IEnumerable<Partida>, IEnumerable<PartidaVM>>(_partidaService.GetAll());
            return View(data);
        }

        public ActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(PartidaVM model)
        {
            _partidaService.Add(Mapper.Map<Partida>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Detalhes(int id)
        {
            return View(Mapper.Map<PartidaVM>(_partidaService.GetById(id)));
        }

        public ActionResult Editar(int id)
        {
            PartidaVM data = Mapper.Map<PartidaVM>(_partidaService.GetById(id));
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(PartidaVM model)
        {
            _partidaService.Update(Mapper.Map<Partida>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Deletar(int id)
        {
            _partidaService.RemoveById(id);
            return RedirectToAction("Index");
        }
    }
}

ChuteCampeao.MVC/Controllers/RodadaController.cs
using AutoMapper;
using ChuteCampeao.Domain.Entites;
using ChuteCampeao.Domain.Interfaces.Services;
using ChuteCampeao.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuteCampeao.MVC.Controllers
{
    public class RodadaController : Controller
    {
        private readonly IRodadaService _rodadaService;

        public RodadaController(IRodadaService rodadaService)
        {
            this._rodadaService = rodadaService;
        }

        public ActionResult Index()
        {
            var data = Mapper.Map<IEnumerable<Rodada>, IEnumerable<RodadaVM>>(_rodadaService.GetAll());
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(RodadaVM model)
        {
            _rodadaService.Add(Mapper.Map<Rodada>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Detalhes(int id)
        {
            return View(Mapper.Map<RodadaVM>(_rodadaService.GetById(id)));
        }

        public ActionResult Editar(int id)
        {
            RodadaVM data = Mapper.Map<RodadaVM>(_rodadaService.GetById(id));
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(RodadaVM model)
        {
            _rodadaService.Update(Mapper.Map<Rodada>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Deletar(int id)
        {
            _rodadaService.RemoveById(id);
            return RedirectToAction("Index");
        }
    }
}

ChuteCampeao.MVC/Controllers/TimeController.cs
using AutoMapper;
using ChuteCampeao.Domain.Entites;
using ChuteCampeao.Domain.Interfaces.Services;
using ChuteCampeao.MVC.Helpers;
using ChuteCampeao.MVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChuteCampeao.MVC.Controllers
{
    public class TimeController : Controller
    {
        private readonly ITimeService _timeService;
        private readonly IEstadioService _estadioService;

        public TimeController(ITimeService timeService, IEstadioService estadioService)
        {
            this._timeService = timeService;
            this._estadioService = estadioService;
        }

        public ActionResult Index()
        {
            var data = Mapper.Map<IEnumerable<Time>, IEnumerable<TimeVM>>(_timeService.GetAll());
            return View(data);
        }

        public ActionResult Criar()
        {
            TimeVM data = new TimeVM() {
                ListaEstadios = _estadioService.BuscarAtivos().Select(x => new SelectListItem()
                {
                    Value = x.Id.ToString(),
                    Text = string.IsNullOrEmpty(x.Apelido) || string.IsNullOrWhiteSpace(x.Apelido) ? x.Nome : x.Apelido
                }),
                LstStatus = Utils.ListarStatus()
            };
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(TimeVM model)
        {
            _timeService.Add(Mapper.Map<Time>(model));
            return RedirectToAction("Index");
        }

        public ActionResult Detalhes(int id)
        {
            return View(Mapper.Map<TimeVM>(_timeService.GetById(id)));
        }

        public ActionResult Editar(int id)
        {
            TimeVM data = Mapper.Map<TimeVM>(_timeService.GetById(id));
            data.ListaEstadios = _estadioService.BuscarAtivos().Select(x => new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = string.IsNullOrEmpty(x.Apelido) || string.IsNullOrWhiteSpace(x.Apelido) ? x.Nome : x.Apelido
            });
            data.LstStatus = Utils.ListarStatus();
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(TimeVM model)
        {
            _timeService.Update(Mapper.Map<Time>(model));
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public void Excluir(int id)
        {
            _timeService.RemoveById(id);
        }
    }
}

ChuteCampeao.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Chute Campeão</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datatables")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/sweetalerts")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/utils")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light custom-navbar">
        @Html.ActionLink("Chute Campeão", "Index", "Home", new { area = "" }, new { @class = "navbar-brand custom-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">@Html.ActionLink("Paginal Inicial", "Index", "Home", null, new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Sobre", "About", "Home", new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Contato", "Contact", "Home", new { @class = "nav-link" })</li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Parametrização <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu dropdown-custom-navbar" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Estádios", "Index", "Estadio", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Times", "Index", "Time", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Campeonatos", "Index", "Campeonato", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Rodadas", "Index", "Rodada", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Partidas", "Index", "Partida", null, new { @class = "dropdown-item" })
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">@Html.ActionLink("Perfil", "Index", "Home", null, new { @class = "nav-link" })</li>

            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Chute Campeão</p>
        </footer>
    </div>
    
    @*@RenderSection("scripts", required: true)*@
</body>
</html>